## Data Cleaning and Handling Missing Values.

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv("large_messy_dataset(Sheet1).csv")
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Non_ usable column,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,701,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,180,978|110|5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,25,544/6218898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,603,4258660422
4,5,George/,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,77,630-179-5207
5,6,Nina_,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,957,NaN
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,659,374|399|7652
7,8,/Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,148,3145713180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,374,2284793231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,111,3890860662
10,11,Quincy_...,30,NaN,60000,2021/03/40,Tom@mail,IT,809,2884619022
11,12,Paul//,35,Pokhara,NaN,2022/07/20,NaN,Finance,478,8859371015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,438,1607104788
13,14,...George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,578,9364984317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,321,7150386033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,197,1349428285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,631,4163922846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,511,731/130/9623
18,19,_Frank,30,,55000,2020-13-01,quincy@gmail,HR,692,811/964/2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,571,8235177960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,300,1711156370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,374,8138371043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,807,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,223,2093387181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,115,2034539017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,728,2203866556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,69,3445714594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,111,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,156,8182230728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,449,6615729527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,791,130/7080/451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,239,8662045040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,688,5334873741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,426,5151438113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,750,8124455397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,550,232-5594165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,794,4578906418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,611,255-0581022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,37,3858923138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,56,1913845444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,294,9536563089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,170,7373451606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,517,1832335988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,968,1698986783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,70,5816256602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,987,2839187771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,679,9613799107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,586,8404782131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,132,7168608910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,191,9068695914

### Droping Data Duplicates

In [7]:
df= df.drop_duplicates()
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Non_ usable column,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,701,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,180,978|110|5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,25,544/6218898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,603,4258660422
4,5,George/,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,77,630-179-5207
5,6,Nina_,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,957,NaN
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,659,374|399|7652
7,8,/Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,148,3145713180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,374,2284793231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,111,3890860662
10,11,Quincy_...,30,NaN,60000,2021/03/40,Tom@mail,IT,809,2884619022
11,12,Paul//,35,Pokhara,NaN,2022/07/20,NaN,Finance,478,8859371015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,438,1607104788
13,14,...George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,578,9364984317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,321,7150386033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,197,1349428285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,631,4163922846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,511,731/130/9623
18,19,_Frank,30,,55000,2020-13-01,quincy@gmail,HR,692,811/964/2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,571,8235177960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,300,1711156370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,374,8138371043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,807,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,223,2093387181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,115,2034539017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,728,2203866556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,69,3445714594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,111,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,156,8182230728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,449,6615729527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,791,130/7080/451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,239,8662045040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,688,5334873741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,426,5151438113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,750,8124455397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,550,232-5594165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,794,4578906418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,611,255-0581022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,37,3858923138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,56,1913845444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,294,9536563089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,170,7373451606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,517,1832335988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,968,1698986783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,70,5816256602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,987,2839187771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,679,9613799107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,586,8404782131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,132,7168608910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,191,9068695914

### Droping columns

In [8]:
df = df.drop(columns = "Non_ usable column")
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978|110|5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,544/6218898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,4258660422
4,5,George/,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina_,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,NaN
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374|399|7652
7,8,/Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,3145713180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,2284793231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,3890860662
10,11,Quincy_...,30,NaN,60000,2021/03/40,Tom@mail,IT,2884619022
11,12,Paul//,35,Pokhara,NaN,2022/07/20,NaN,Finance,8859371015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,1607104788
13,14,...George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,9364984317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,7150386033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,1349428285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,4163922846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731/130/9623
18,19,_Frank,30,,55000,2020-13-01,quincy@gmail,HR,811/964/2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,8235177960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,1711156370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,8138371043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,2093387181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,2034539017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,2203866556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,3445714594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,8182230728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,6615729527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130/7080/451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,8662045040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,5334873741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,5151438113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,8124455397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-5594165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,4578906418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-0581022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,3858923138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,1913845444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,9536563089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,7373451606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,1832335988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,1698986783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,5816256602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,2839187771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,9613799107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,8404782131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,7168608910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,9068695914

### Strip

In [9]:
#(note: lstrip: Remove unwanted from left side, rstrip: Remove unwanted from right side, strip: reomove unwanted from both side)
df["Name"].str.lstrip("/") #It remove / from left of Name column

0         George
1            Tom
2           Isha
3            Oli
4        George/
5          Nina_
6          David
7           Mina
8          David
9           Jake
10    Quincy_...
11        Paul//
12          Nina
13     ...George
14          Isha
15         Frank
16           Eve
17         Alice
18        _Frank
19          Isha
20          Nina
21         Frank
22           Eve
23          Mina
24          Nina
25        Quincy
26          Ravi
27          Isha
28         Frank
29          Paul
30          Jake
31         Frank
32          Hira
33        George
34          Isha
35          Isha
36          Jake
37           Bob
38          Mina
39        Quincy
40        Quincy
41         David
42         Frank
43           Tom
44         Alice
45         Kiran
46          Ravi
47           Tom
48           Tom
49           Sam
Name: Name, dtype: object

In [10]:
df["Name"].str.rstrip("...") #It remove ... from right of Name column

0        George
1           Tom
2          Isha
3           Oli
4       George/
5         Nina_
6         David
7         /Mina
8         David
9          Jake
10      Quincy_
11       Paul//
12         Nina
13    ...George
14         Isha
15        Frank
16          Eve
17        Alice
18       _Frank
19         Isha
20         Nina
21        Frank
22          Eve
23         Mina
24         Nina
25       Quincy
26         Ravi
27         Isha
28        Frank
29         Paul
30         Jake
31        Frank
32         Hira
33       George
34         Isha
35         Isha
36         Jake
37          Bob
38         Mina
39       Quincy
40       Quincy
41        David
42        Frank
43          Tom
44        Alice
45        Kiran
46         Ravi
47          Tom
48          Tom
49          Sam
Name: Name, dtype: object

In [11]:
df["Name"].str.strip("_")#It roemove _from both side

0         George
1            Tom
2           Isha
3            Oli
4        George/
5           Nina
6          David
7          /Mina
8          David
9           Jake
10    Quincy_...
11        Paul//
12          Nina
13     ...George
14          Isha
15         Frank
16           Eve
17         Alice
18         Frank
19          Isha
20          Nina
21         Frank
22           Eve
23          Mina
24          Nina
25        Quincy
26          Ravi
27          Isha
28         Frank
29          Paul
30          Jake
31         Frank
32          Hira
33        George
34          Isha
35          Isha
36          Jake
37           Bob
38          Mina
39        Quincy
40        Quincy
41         David
42         Frank
43           Tom
44         Alice
45         Kiran
46          Ravi
47           Tom
48           Tom
49           Sam
Name: Name, dtype: object

In [12]:
df["Name"]= df["Name"].str.strip("123._/") #It remove the numbers, ., _, / from the Name column
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978|110|5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,544/6218898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,4258660422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,NaN
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374|399|7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,3145713180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,2284793231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,3890860662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,2884619022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,8859371015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,1607104788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,9364984317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,7150386033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,1349428285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,4163922846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731/130/9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811/964/2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,8235177960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,1711156370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,8138371043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,2093387181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,2034539017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,2203866556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,3445714594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,8182230728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,6615729527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130/7080/451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,8662045040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,5334873741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,5151438113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,8124455397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-5594165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,4578906418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-0581022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,3858923138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,1913845444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,9536563089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,7373451606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,1832335988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,1698986783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,5816256602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,2839187771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,9613799107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,8404782131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,7168608910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,9068695914

### Cleaning / Standardizing phone numbers

In [54]:
#I wants all the phone numbers in 111-111-1111 this format 
#df["Phone_number"].apply(lambda x: str(x))
#df["Phone_number"].apply(lambda)

In [13]:
df["Phone_number"] = df["Phone_number"].str.replace(r'[^0-9]', '', regex=True)
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,7103094329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,9781105804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,5446218898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,4258660422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,6301795207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,NaN
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,3743997652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,3145713180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,2284793231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,3890860662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,2884619022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,8859371015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,1607104788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,9364984317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,7150386033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,1349428285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,4163922846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,7311309623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,8119642824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,8235177960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,1711156370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,8138371043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,5041018147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,2093387181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,2034539017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,2203866556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,3445714594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,4529617827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,8182230728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,6615729527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,1307080451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,8662045040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,5334873741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,5151438113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,8124455397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,2325594165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,4578906418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,2550581022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,3858923138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,1913845444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,9536563089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,7373451606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,1832335988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,1698986783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,5816256602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,2839187771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,9613799107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,8404782131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,7168608910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,9068695914

In [14]:
df["Phone_number"]=df["Phone_number"].apply(lambda x: str(x))
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,7103094329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,9781105804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,5446218898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,4258660422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,6301795207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,nan
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,3743997652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,3145713180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,2284793231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,3890860662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,2884619022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,8859371015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,1607104788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,9364984317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,7150386033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,1349428285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,4163922846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,7311309623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,8119642824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,8235177960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,1711156370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,8138371043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,5041018147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,2093387181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,2034539017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,2203866556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,3445714594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,4529617827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,8182230728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,6615729527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,1307080451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,8662045040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,5334873741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,5151438113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,8124455397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,2325594165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,4578906418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,2550581022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,3858923138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,1913845444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,9536563089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,7373451606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,1832335988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,1698986783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,5816256602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,2839187771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,9613799107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,8404782131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,7168608910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,9068695914

In [15]:
df["Phone_number"]=df["Phone_number"].apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:10])
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,544-621-8898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,nan--
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,515-143-8113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,961-379-9107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [16]:
df["Phone_number"]=df["Phone_number"].replace('nan--','')
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,NaN,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,NaN,544-621-8898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,NaN,515-143-8113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,NaN,961-379-9107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,NaN,NaN,NaN,George@,NaN,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [17]:
df["Department"]=df["Department"].apply(lambda x: str(x))
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,nan,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,nan,544-621-8898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,nan,515-143-8113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,nan,961-379-9107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,NaN,NaN,NaN,George@,nan,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [18]:
df["Department"]=df["Department"].replace('nan','')
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,NaN,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,NaN,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,NaN,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,NaN,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,NaN,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,NaN,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,NaN,NaN,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,NaN,NaN,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,NaN,NaN,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,NaN,NaN,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,NaN,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,NaN,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,NaN,NaN,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,NaN,NaN,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,NaN,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,NaN,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,NaN,NaN,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,NaN,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,NaN,NaN,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [19]:
df["Age"]=df["Age"].apply(lambda x: str(x))
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,nan,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,nan,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,nan,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,nan,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,nan,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,nan,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,nan,NaN,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,nan,NaN,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,nan,NaN,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,nan,NaN,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,nan,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,nan,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,nan,NaN,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,nan,NaN,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,nan,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,nan,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,nan,NaN,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,nan,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,NaN,NaN,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [20]:
df["Age"]=df["Age"].replace('nan','')
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,,NaN,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,NaN,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,NaN,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,NaN,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,NaN,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,,NaN,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,,NaN,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,NaN,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,NaN,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,,NaN,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,NaN,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,NaN,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,,NaN,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,NaN,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,NaN,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,,NaN,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,NaN,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,NaN,NaN,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [21]:
df["City"]=df["City"].apply(lambda x: str(x))
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,,nan,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,nan,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,nan,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,nan,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,nan,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,,nan,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,,nan,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,nan,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,nan,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,,nan,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,nan,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,nan,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,,nan,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,nan,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,nan,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,,nan,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,nan,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,nan,NaN,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [22]:
df["City"]=df["City"].replace('nan','')
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,,,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,NaN,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,NaN,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,NaN,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,,,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,,,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,,,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,,,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,NaN,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,NaN,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,,,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,,NaN,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,NaN,2022/07/20,NaN,Finance,906-869-5914

In [23]:
df["Salary"]=df["Salary"].apply(lambda x: str(x))
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,,,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,nan,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,nan,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,nan,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,,,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,,,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,,,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,,,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,nan,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,nan,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,,,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,,nan,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,nan,2022/07/20,NaN,Finance,906-869-5914

In [24]:
df["Salary"]=df["Salary"].replace('nan','')
df

,ID,Name,Age,City,Salary,Join_Date,Email,Department,Phone_number
0,1,George,40,Lalitpur,thousand,2021-01-10,bob@gmail,,710-309-4329
1,2,Tom,,,NaN,2020-13-01,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,2021-01-10,Luna@mail,,544-621-8898
3,4,Oli,,,55k,2021-01-10,Nina@mail,HR,425-866-0422
4,5,George,,Birgunj,70000,2020-13-01,Jake@mail,Finance,630-179-5207
5,6,Nina,,Butwal,thousand,2020-13-01,Eve@mail,Sales,
6,7,David,45,Biratnagar,NaN,2020-15-10,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,2020-13-01,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,,2020-13-01,NaN,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,NaN,David@mail,IT,389-086-0662
10,11,Quincy,30,,60000,2021/03/40,Tom@mail,IT,288-461-9022
11,12,Paul,35,Pokhara,,2022/07/20,NaN,Finance,885-937-1015
12,13,Nina,40,Butwal,thousand,2020-13-01,frank@gmail,HR,160-710-4788
13,14,George,30,Biratnagar,55k,2020-13-01,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,,2021-01-10,Eve@mail,Sales,715-038-6033
15,16,Frank,,,70000,2020/03/15,NaN,Sales,134-942-8285
16,17,Eve,,,NaN,2020-15-10,Luna@,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,2021-01-10,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,2020-13-01,quincy@gmail,HR,811-964-2824
19,20,Isha,,,55000,NaN,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,thousand,2022/07/20,hira@gmail,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,2021/03/40,Jake@,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,2020-15-10,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,15-06-2022,NaN,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,05/10/2020,oli@gmail,HR,203-453-9017
25,26,Quincy,30,,thousand,2021/03/40,Bob@mail,HR,220-386-6556
26,27,Ravi,,,55000,05/10/2020,Kiran@mail,IT,344-571-4594
27,28,Isha,,Butwal,60000,2021-01-10,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,2020-13-01,NaN,IT,818-223-0728
29,30,Paul,35,,60000,15-06-2022,Ravi@mail,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,2021/03/40,NaN,Finance,130-708-0451
31,32,Frank,,,55000,2021/03/40,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,2021-01-10,Frank@mail,Finance,533-487-3741
33,34,George,30,,55k,2021-01-10,Nina@mail,,515-143-8113
34,35,Isha,,,55k,2020/03/15,Kiran@mail,Sales,812-445-5397
35,36,Isha,45,,55000,2021-01-10,quincy@gmail,Finance,232-559-4165
36,37,Jake,,Birgunj,thousand,NaN,NaN,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,2021-01-10,Jake@mail,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,2021-01-10,david@gmail,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,05/10/2020,Hira@mail,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,,2021/03/40,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,15-06-2022,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,2020-15-10,Bob@mail,HR,183-233-5988
43,44,Tom,30,Butwal,,05/10/2020,NaN,HR,169-898-6783
44,45,Alice,,,55k,05/10/2020,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,15-06-2022,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,2021-01-10,Eve@,,961-379-9107
47,48,Tom,,Butwal,60000,NaN,NaN,IT,840-478-2131
48,49,Tom,thirty,,,NaN,George@,,716-860-8910
49,50,Sam,30,Lalitpur,,2022/07/20,NaN,Finance,906-869-5914

In [49]:
df["Salary"]=df["Salary"].replace('thousand','1000')
df["Salary"]=df["Salary"].replace('55k','55000')
df

,ID,Name,Age,City,Salary,Email,Department,Phone_number
0,1,George,40,Lalitpur,1000,bob@gmail.com,,710-309-4329
1,2,Tom,,,NaN,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,luna@mail.com,,544-621-8898
3,4,Oli,,,55000,nina@mail.com,HR,425-866-0422
4,5,George,,Birgunj,70000,jake@mail.com,Finance,630-179-5207
5,6,Nina,,Butwal,1000,eve@mail.com,Sales,
6,7,David,45,Biratnagar,NaN,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,,na@na.com,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,david@mail.com,IT,389-086-0662
10,11,Quincy,30,,60000,tom@mail.com,IT,288-461-9022
11,12,Paul,35,Pokhara,,na@na.com,Finance,885-937-1015
12,13,Nina,40,Butwal,1000,frank@gmail.com,HR,160-710-4788
13,14,George,30,Biratnagar,55000,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,,eve@mail.com,Sales,715-038-6033
15,16,Frank,,,70000,na@na.com,Sales,134-942-8285
16,17,Eve,,,NaN,luna@.com,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,quincy@gmail.com,HR,811-964-2824
19,20,Isha,,,55000,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,1000,hira@gmail.com,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,jake@.com,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,na@na.com,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,oli@gmail.com,HR,203-453-9017
25,26,Quincy,30,,1000,bob@mail.com,HR,220-386-6556
26,27,Ravi,,,55000,kiran@mail.com,IT,344-571-4594
27,28,Isha,,Butwal,60000,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,na@na.com,IT,818-223-0728
29,30,Paul,35,,60000,ravi@mail.com,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,na@na.com,Finance,130-708-0451
31,32,Frank,,,55000,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,frank@mail.com,Finance,533-487-3741
33,34,George,30,,55000,nina@mail.com,,515-143-8113
34,35,Isha,,,55000,kiran@mail.com,Sales,812-445-5397
35,36,Isha,45,,55000,quincy@gmail.com,Finance,232-559-4165
36,37,Jake,,Birgunj,1000,na@na.com,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,jake@mail.com,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,david@gmail.com,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,hira@mail.com,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,bob@mail.com,HR,183-233-5988
43,44,Tom,30,Butwal,,na@na.com,HR,169-898-6783
44,45,Alice,,,55000,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,eve@.com,,961-379-9107
47,48,Tom,,Butwal,60000,na@na.com,IT,840-478-2131
48,49,Tom,thirty,,,george@.com,,716-860-8910
49,50,Sam,30,Lalitpur,,na@na.com,Finance,906-869-5914

In [46]:
df["Email"]=df["Email"].apply(lambda x: str(x))
df

,ID,Name,Age,City,Salary,Email,Department,Phone_number
0,1,George,40,Lalitpur,1000,bob@gmail.com,,710-309-4329
1,2,Tom,,,NaN,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,luna@mail.com,,544-621-8898
3,4,Oli,,,55000,nina@mail.com,HR,425-866-0422
4,5,George,,Birgunj,70000,jake@mail.com,Finance,630-179-5207
5,6,Nina,,Butwal,1000,eve@mail.com,Sales,
6,7,David,45,Biratnagar,NaN,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,,na@na.com,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,david@mail.com,IT,389-086-0662
10,11,Quincy,30,,60000,tom@mail.com,IT,288-461-9022
11,12,Paul,35,Pokhara,,na@na.com,Finance,885-937-1015
12,13,Nina,40,Butwal,1000,frank@gmail.com,HR,160-710-4788
13,14,George,30,Biratnagar,55000,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,,eve@mail.com,Sales,715-038-6033
15,16,Frank,,,70000,na@na.com,Sales,134-942-8285
16,17,Eve,,,NaN,luna@.com,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,quincy@gmail.com,HR,811-964-2824
19,20,Isha,,,55000,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,1000,hira@gmail.com,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,jake@.com,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,na@na.com,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,oli@gmail.com,HR,203-453-9017
25,26,Quincy,30,,1000,bob@mail.com,HR,220-386-6556
26,27,Ravi,,,55000,kiran@mail.com,IT,344-571-4594
27,28,Isha,,Butwal,60000,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,na@na.com,IT,818-223-0728
29,30,Paul,35,,60000,ravi@mail.com,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,na@na.com,Finance,130-708-0451
31,32,Frank,,,55000,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,frank@mail.com,Finance,533-487-3741
33,34,George,30,,55000,nina@mail.com,,515-143-8113
34,35,Isha,,,55000,kiran@mail.com,Sales,812-445-5397
35,36,Isha,45,,55000,quincy@gmail.com,Finance,232-559-4165
36,37,Jake,,Birgunj,1000,na@na.com,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,jake@mail.com,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,david@gmail.com,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,hira@mail.com,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,bob@mail.com,HR,183-233-5988
43,44,Tom,30,Butwal,,na@na.com,HR,169-898-6783
44,45,Alice,,,55000,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,eve@.com,,961-379-9107
47,48,Tom,,Butwal,60000,na@na.com,IT,840-478-2131
48,49,Tom,thirty,,,george@.com,,716-860-8910
49,50,Sam,30,Lalitpur,,na@na.com,Finance,906-869-5914

In [47]:
df["Email"]=df["Email"].replace('nan','')
df

,ID,Name,Age,City,Salary,Email,Department,Phone_number
0,1,George,40,Lalitpur,1000,bob@gmail.com,,710-309-4329
1,2,Tom,,,NaN,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,luna@mail.com,,544-621-8898
3,4,Oli,,,55000,nina@mail.com,HR,425-866-0422
4,5,George,,Birgunj,70000,jake@mail.com,Finance,630-179-5207
5,6,Nina,,Butwal,1000,eve@mail.com,Sales,
6,7,David,45,Biratnagar,NaN,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,,na@na.com,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,david@mail.com,IT,389-086-0662
10,11,Quincy,30,,60000,tom@mail.com,IT,288-461-9022
11,12,Paul,35,Pokhara,,na@na.com,Finance,885-937-1015
12,13,Nina,40,Butwal,1000,frank@gmail.com,HR,160-710-4788
13,14,George,30,Biratnagar,55000,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,,eve@mail.com,Sales,715-038-6033
15,16,Frank,,,70000,na@na.com,Sales,134-942-8285
16,17,Eve,,,NaN,luna@.com,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,quincy@gmail.com,HR,811-964-2824
19,20,Isha,,,55000,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,1000,hira@gmail.com,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,jake@.com,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,na@na.com,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,oli@gmail.com,HR,203-453-9017
25,26,Quincy,30,,1000,bob@mail.com,HR,220-386-6556
26,27,Ravi,,,55000,kiran@mail.com,IT,344-571-4594
27,28,Isha,,Butwal,60000,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,na@na.com,IT,818-223-0728
29,30,Paul,35,,60000,ravi@mail.com,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,na@na.com,Finance,130-708-0451
31,32,Frank,,,55000,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,frank@mail.com,Finance,533-487-3741
33,34,George,30,,55000,nina@mail.com,,515-143-8113
34,35,Isha,,,55000,kiran@mail.com,Sales,812-445-5397
35,36,Isha,45,,55000,quincy@gmail.com,Finance,232-559-4165
36,37,Jake,,Birgunj,1000,na@na.com,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,jake@mail.com,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,david@gmail.com,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,hira@mail.com,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,bob@mail.com,HR,183-233-5988
43,44,Tom,30,Butwal,,na@na.com,HR,169-898-6783
44,45,Alice,,,55000,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,eve@.com,,961-379-9107
47,48,Tom,,Butwal,60000,na@na.com,IT,840-478-2131
48,49,Tom,thirty,,,george@.com,,716-860-8910
49,50,Sam,30,Lalitpur,,na@na.com,Finance,906-869-5914

In [44]:
import re
def clean_email(email):
    email = str(email).strip().lower()     # remove spaces + lowercase
    # Split user and domain
    user, domain = email.split("@")[0], email.split("@")[-1]
    # Remove unwanted characters
    user = re.sub(r'[^a-z0-9._]', '', user)
    domain = re.sub(r'[^a-z0-9.]', '', domain)
    # If domain missing extension, add ".com"
    if "." not in domain:
        domain = domain + ".com"
    return user + "@" + domain

In [45]:
df["Email"] = df["Email"].apply(clean_email)
df

,ID,Name,Age,City,Salary,Email,Department,Phone_number
0,1,George,40,Lalitpur,1000,bob@gmail.com,,710-309-4329
1,2,Tom,,,NaN,luna@gmail.com,Sales,978-110-5804
2,3,Isha,45,,70000,luna@mail.com,,544-621-8898
3,4,Oli,,,55000,nina@mail.com,HR,425-866-0422
4,5,George,,Birgunj,70000,jake@mail.com,Finance,630-179-5207
5,6,Nina,,Butwal,1000,eve@mail.com,Sales,
6,7,David,45,Biratnagar,NaN,david@mail.com,HR,374-399-7652
7,8,Mina,40,,60000,quincy@gmail.com,IT,314-571-3180
8,9,David,30,,,na@na.com,Sales,228-479-3231
9,10,Jake,25,Lalitpur,50000,david@mail.com,IT,389-086-0662
10,11,Quincy,30,,60000,tom@mail.com,IT,288-461-9022
11,12,Paul,35,Pokhara,,na@na.com,Finance,885-937-1015
12,13,Nina,40,Butwal,1000,frank@gmail.com,HR,160-710-4788
13,14,George,30,Biratnagar,55000,charlie@yahoo.com,Sales,936-498-4317
14,15,Isha,,Biratnagar,,eve@mail.com,Sales,715-038-6033
15,16,Frank,,,70000,na@na.com,Sales,134-942-8285
16,17,Eve,,,NaN,luna@.com,HR,416-392-2846
17,18,Alice,35,Birgunj,70000,kiran@mail.com,HR,731-130-9623
18,19,Frank,30,,55000,quincy@gmail.com,HR,811-964-2824
19,20,Isha,,,55000,nina@gmail.com,Finance,823-517-7960
20,21,Nina,35,,1000,hira@gmail.com,IT,171-115-6370
21,22,Frank,25,Kathmandu,NaN,jake@.com,Sales,813-837-1043
22,23,Eve,thirty,Butwal,50000,jake@gmail.com,Finance,504-101-8147
23,24,Mina,,,55000,na@na.com,HR,209-338-7181
24,25,Nina,40,Biratnagar,50000,oli@gmail.com,HR,203-453-9017
25,26,Quincy,30,,1000,bob@mail.com,HR,220-386-6556
26,27,Ravi,,,55000,kiran@mail.com,IT,344-571-4594
27,28,Isha,,Butwal,60000,charlie@yahoo.com,Finance,452-961-7827
28,29,Frank,25,Butwal,NaN,na@na.com,IT,818-223-0728
29,30,Paul,35,,60000,ravi@mail.com,HR,661-572-9527
30,31,Jake,thirty,Pokhara,60000,na@na.com,Finance,130-708-0451
31,32,Frank,,,55000,alice@yahoo.com,IT,866-204-5040
32,33,Hira,,,60000,frank@mail.com,Finance,533-487-3741
33,34,George,30,,55000,nina@mail.com,,515-143-8113
34,35,Isha,,,55000,kiran@mail.com,Sales,812-445-5397
35,36,Isha,45,,55000,quincy@gmail.com,Finance,232-559-4165
36,37,Jake,,Birgunj,1000,na@na.com,HR,457-890-6418
37,38,Bob,45,Kathmandu,55000,jake@mail.com,Sales,255-058-1022
38,39,Mina,,Biratnagar,50000,david@gmail.com,IT,385-892-3138
39,40,Quincy,30,Butwal,70000,hira@mail.com,Sales,191-384-5444
40,41,Quincy,40,Kathmandu,,nina@mail.com,Finance,953-656-3089
41,42,David,30,,60000,isha@yahoo.com,IT,737-345-1606
42,43,Frank,45,,NaN,bob@mail.com,HR,183-233-5988
43,44,Tom,30,Butwal,,na@na.com,HR,169-898-6783
44,45,Alice,,,55000,paul@yahoo.com,Sales,581-625-6602
45,46,Kiran,35,Kathmandu,55000,mina@yahoo.com,IT,283-918-7771
46,47,Ravi,thirty,,NaN,eve@.com,,961-379-9107
47,48,Tom,,Butwal,60000,na@na.com,IT,840-478-2131
48,49,Tom,thirty,,,george@.com,,716-860-8910
49,50,Sam,30,Lalitpur,,na@na.com,Finance,906-869-5914